name: C++ CI

on: # 觸發條件
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build
      run: make

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: hello-program
        path: ./hello  # 上傳編譯後的可執行文件
