name: C++ CI

on: # 觸發條件
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest  # 主機環境仍是最新版
    container:
      image: ubuntu:18.04  # 在容器內運行舊版系統
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y g++ make

      - name: Build
        run: make

      - name: Run
        run: ./hello

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: hello-program
        path: ./hello  # 上傳編譯後的可執行文件
